"""
seasonal_filter.py — ISO-week-based seasonal presence filter.

Loads ``uk_seasonal_filter.json`` (or a user-specified override) and provides
a fast O(1) check of whether a species is expected in Great Britain during the
current ISO week.

Data source
-----------
The default JSON is generated by ``build_uk_seasonal_filter.py`` from GBIF
Great Britain occurrence data — a genuinely UK-specific source, free of the
North American eBird bias that affects the BirdNET metadata model.

To customise for your site, copy ``uk_seasonal_filter.json`` to e.g.
``uk_seasonal_filter_local.json``, edit it, and point ``[seasonal_filter]
filter_json`` in ``config.toml`` at the copy.

ISO week scale
--------------
Weeks are standard ISO 8601 week numbers (1–52, occasionally 53).  At runtime::

    week = datetime.now(UTC).isocalendar()[1]   # 1–52 (or 53 in long years)

Week 53 (which appears roughly every 5–6 years) is clamped to 52 so it matches
the JSON, which only stores weeks 1–52.

Filter logic
------------
- Species **absent from the JSON** ``species`` dict → **no restriction**
  (year-round residents, or species with sparse GBIF data).
- Species **present in the JSON** → allowed only if ``current_week`` is in
  their allowed-weeks set.
- The filter is applied after the BOU allowlist (Step 3b) and before the
  per-species confidence threshold (Step 4).

Usage::

    from seasonal_filter import SeasonalFilter, current_iso_week

    sf = SeasonalFilter()          # loads JSON once at construction
    week = current_iso_week()      # ISO week of today
    if not sf.check(species, week):
        continue                   # out-of-season: skip this candidate
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

_DEFAULT_JSON = Path(__file__).parent / "uk_seasonal_filter.json"


def current_iso_week(ts: datetime | None = None) -> int:
    """Return the ISO 8601 week number (1–52, clamped from 53) for *ts*.

    Args:
        ts: UTC datetime.  If ``None``, uses the current UTC time.

    Returns:
        ISO week number in the range 1–52.  Week 53 (occurs in long years
        such as 2020 and 2026) is clamped to 52 so it always matches the
        week range stored in the JSON.
    """
    if ts is None:
        ts = datetime.now(timezone.utc)
    week = ts.isocalendar()[1]
    return min(week, 52)


class SeasonalFilter:
    """Runtime seasonal presence filter backed by a JSON week-list file.

    The JSON file is generated by ``build_uk_seasonal_filter.py`` and
    contains, for each seasonally-restricted species, the ISO week numbers
    (1–52) during which it is expected in Great Britain.

    Attributes:
        enabled:  Whether the filter is active.  When ``False``, :meth:`check`
                  always returns ``True``.
        json_path: Path of the loaded JSON file (for logging/debugging).
    """

    def __init__(self, enabled: bool = True, json_path: Path | None = None) -> None:
        self.enabled   = enabled
        self.json_path = json_path or _DEFAULT_JSON
        # {birdnet_common_name: frozenset[int]} — week sets from JSON.
        self._allowed: dict[str, frozenset[int]] = {}

        if not self.enabled:
            return

        if not self.json_path.exists():
            logger.warning(
                "seasonal_filter: %s not found — seasonal filtering disabled. "
                "Run build_uk_seasonal_filter.py to generate it.",
                self.json_path,
            )
            self.enabled = False
            return

        try:
            with open(self.json_path) as fh:
                data: dict = json.load(fh)
        except (json.JSONDecodeError, OSError) as exc:
            logger.error(
                "seasonal_filter: failed to load %s: %s", self.json_path, exc
            )
            self.enabled = False
            return

        species_data: dict[str, list[int]] = data.get("species", {})
        self._allowed = {
            name: frozenset(weeks)
            for name, weeks in species_data.items()
        }

        week_scale = data.get("_metadata", {}).get("week_scale", "?")
        logger.info(
            "seasonal_filter: loaded %d species with restrictions from %s (week scale: %s)",
            len(self._allowed),
            self.json_path.name,
            week_scale,
        )

    def check(self, species: str, week: int) -> bool:
        """Return ``True`` if *species* is expected in *week*.

        Args:
            species: BirdNET common name (exact case, as returned by
                     ``run_inference()``).
            week:    ISO week number 1–52 (use :func:`current_iso_week`).

        Returns:
            ``True`` when the species is allowed (either unrestricted or
            within its expected season).  ``False`` when the filter is loaded
            and the species has a restriction that excludes the given week.
        """
        if not self.enabled:
            return True

        allowed_weeks = self._allowed.get(species)
        if allowed_weeks is None:
            # Not listed → no restriction → allow.
            return True

        return week in allowed_weeks
